@echo off
echo Starting CareFusion AI Services...
start /min START_BACKEND.bat
echo Waiting for services to initialize...
timeout /t 5
echo Launching CareFusion AI App...
start chrome --app=http://localhost:5173
exit
